# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apply2Canada
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  一些帮助你申请加拿大学校的文章,所有文章未经原作者许可禁止转载。
# baseurl: "http://apply2canada.github.io" # the subpath of your site, e.g. /blog
url: "http://apply2canada.github.io" # the base hostname & protocol for your site

github_username:  apply2canada
# google_analytic_id:
# disqus_name:

permalink: /:categories/:title
paginate: 5
paginate_path: /page/:num

# jekyll seo tag settings
logo: assets/images/example-image.png
# twitter:
#   username: jekyllrb

# Build settings
markdown: kramdown
sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
